### ISSUE TITLE
define things from Senritsu "Unidentified" folder

### ISSUE THREAD

**Issue by senpaizuri3** [trigger-death/GrisaiaExtractor#3]
Most of the images are coming off as a part of the `Unidentified` folder, likely due to not considering characters take place exclusively in this game like sprites for Major Isabella Fitzgerald (`iza`), Marion Garland (`mro`), and Ramon Noboa (`nob`). There are also some BGs with the prefix `bgt` which are backgrounds not placed in the background folder. The CGs are given the prefix `evt`, which are also placed in `Unidentified`. You can have them in a `Story/CG` directory like you do for Afterglow (Zankou).

**Comment by trigger-segfault** [comment]
Just for clarification, all names listed are First Last name, correct? I want to keep consistency with the sorting.

**Comment by senpaizuri3** [comment]
Yes. The names of the characters are American in the game, and so the names are in first-last notation.

**Comment by trigger-segfault** [comment]
Could you give some examples of backgrounds prefixed with `bgt`? I need to know what regex to use to search for them.

**Comment by trigger-segfault** [comment]
Alright, I've released the latest version which should add the requested categorization, you can use the `resort` option in `int/hg3/resort` to just update the categorization of already-extracted pngs.
